// Package backup implements the encrypted, single-message Mesh recovery archive.
package backup

import (
	"bytes"
	"crypto/aes"
	"crypto/cipher"
	cryptorand "crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"time"

	"crypto/hkdf"
)

const (
	// MaxArchiveSize is the maximum complete binary envelope accepted by Open.
	MaxArchiveSize = 80 << 20

	MaxControlStateSize  = 64 << 20
	MaxIdentityStateSize = 8 << 20
	// RootKeySize is the exact byte length of an independently generated root
	// backup key.
	RootKeySize = 32

	fixedHeaderSize  = 16
	saltSize         = 32
	lengthFieldSize  = 8
	envelopeHeadSize = fixedHeaderSize + saltSize + lengthFieldSize
	manifestSizeSize = 4
	maxManifestSize  = 64 << 10
	gcmOverhead      = 28

	backupKDFInfo = "mesh-backup-aes-256-gcm-v1"
)

var (
	envelopeMagic = [fixedHeaderSize]byte{'M', 'E', 'S', 'H', '-', 'B', 'A', 'C', 'K', 'U', 'P', '-', 'V', '1', 0, 0}

	// ErrAuthentication means the archive did not authenticate under the
	// supplied root backup key. It intentionally does not distinguish a wrong
	// key from authenticated-envelope tampering.
	ErrAuthentication = errors.New("backup archive authentication failed")
)

// Source contains exact bytes captured from a stopped or otherwise
// coordinated control plane. Seal never modifies or retains these slices.
type Source struct {
	StateJSON         []byte
	IdentityStateJSON []byte
	MasterKey         []byte
	AdminToken        []byte
	ControlVersion    uint64
	IdentitySchema    string
}

// Contents is a fully authenticated and validated recovery archive. All byte
// slices are detached from both the caller's envelope and internal plaintext.
type Contents struct {
	Manifest          Manifest
	StateJSON         []byte
	IdentityStateJSON []byte
	MasterKey         []byte
	AdminToken        []byte
}

// Codec holds the capture-time dependencies used while sealing archives.
// NewCodec is the production constructor.
type Codec struct {
	random io.Reader
	now    func() time.Time
}

// NewCodec returns a codec backed by crypto/rand and the system clock.
func NewCodec() *Codec {
	return &Codec{random: cryptorand.Reader, now: time.Now}
}

// NewCodecForTesting permits deterministic capture metadata in tests. GCM
// nonces remain generated by cipher.NewGCMWithRandomNonce using crypto/rand.
// Production code should use NewCodec or the package-level functions.
func NewCodecForTesting(random io.Reader, now func() time.Time) (*Codec, error) {
	if random == nil || now == nil {
		return nil, errors.New("backup test codec requires both entropy and a clock")
	}
	return &Codec{random: random, now: now}, nil
}

// Seal creates an authenticated recovery archive using production entropy.
func Seal(rootKey []byte, source Source) ([]byte, Manifest, error) {
	return NewCodec().Seal(rootKey, source)
}

// Open authenticates, decrypts, and strictly validates a recovery archive.
func Open(rootKey, envelope []byte) (Contents, error) {
	return NewCodec().Open(rootKey, envelope)
}

// Inspect authenticates and strictly validates an archive, returning only its
// non-secret manifest metadata.
func Inspect(rootKey, envelope []byte) (Manifest, error) {
	return NewCodec().Inspect(rootKey, envelope)
}

// Seal creates an authenticated recovery archive. The returned envelope and
// manifest are detached from source.
func (c *Codec) Seal(rootKey []byte, source Source) ([]byte, Manifest, error) {
	if err := validateRootKey(rootKey); err != nil {
		return nil, Manifest{}, err
	}
	if c == nil || c.random == nil || c.now == nil {
		return nil, Manifest{}, errors.New("backup codec is not initialized")
	}
	if err := validateSource(source); err != nil {
		return nil, Manifest{}, err
	}

	manifest, err := c.newManifest(source)
	if err != nil {
		return nil, Manifest{}, err
	}
	manifestJSON, err := encodeManifest(manifest)
	if err != nil {
		return nil, Manifest{}, err
	}
	plaintext, err := encodePlaintext(manifestJSON, source)
	if err != nil {
		return nil, Manifest{}, err
	}
	defer clear(plaintext)

	ciphertextLength := len(plaintext) + gcmOverhead
	if ciphertextLength > MaxArchiveSize-envelopeHeadSize {
		return nil, Manifest{}, errors.New("backup archive exceeds its size limit")
	}

	header := make([]byte, envelopeHeadSize)
	copy(header[:fixedHeaderSize], envelopeMagic[:])
	if _, err := io.ReadFull(c.random, header[fixedHeaderSize:fixedHeaderSize+saltSize]); err != nil {
		return nil, Manifest{}, fmt.Errorf("generate backup salt: %w", err)
	}
	binary.BigEndian.PutUint64(header[fixedHeaderSize+saltSize:], uint64(ciphertextLength))

	aead, derivedKey, err := archiveAEAD(rootKey, header[fixedHeaderSize:fixedHeaderSize+saltSize])
	if err != nil {
		return nil, Manifest{}, err
	}
	defer clear(derivedKey)
	ciphertext := aead.Seal(nil, nil, plaintext, header)
	if len(ciphertext) != ciphertextLength {
		clear(ciphertext)
		return nil, Manifest{}, errors.New("backup cipher returned an unexpected message length")
	}
	envelope := make([]byte, 0, len(header)+len(ciphertext))
	envelope = append(envelope, header...)
	envelope = append(envelope, ciphertext...)
	clear(ciphertext)
	return envelope, cloneManifest(manifest), nil
}

// Open authenticates, decrypts, and strictly validates a recovery archive.
func (c *Codec) Open(rootKey, envelope []byte) (Contents, error) {
	if c == nil {
		return Contents{}, errors.New("backup codec is not initialized")
	}
	plaintext, err := decryptEnvelope(rootKey, envelope)
	if err != nil {
		return Contents{}, err
	}
	defer clear(plaintext)
	contents, err := decodePlaintext(plaintext)
	if err != nil {
		return Contents{}, err
	}
	return contents, nil
}

// Inspect authenticates and validates the entire archive before returning a
// detached manifest. Body digests and credential encodings are not skipped.
func (c *Codec) Inspect(rootKey, envelope []byte) (Manifest, error) {
	if c == nil {
		return Manifest{}, errors.New("backup codec is not initialized")
	}
	contents, err := c.Open(rootKey, envelope)
	if err != nil {
		return Manifest{}, err
	}
	clear(contents.StateJSON)
	clear(contents.IdentityStateJSON)
	clear(contents.MasterKey)
	clear(contents.AdminToken)
	return cloneManifest(contents.Manifest), nil
}

func decryptEnvelope(rootKey, envelope []byte) ([]byte, error) {
	if err := validateRootKey(rootKey); err != nil {
		return nil, err
	}
	if len(envelope) < envelopeHeadSize+gcmOverhead || len(envelope) > MaxArchiveSize {
		return nil, errors.New("backup envelope has an invalid size")
	}
	header := envelope[:envelopeHeadSize]
	if !bytes.Equal(header[:fixedHeaderSize], envelopeMagic[:]) {
		return nil, errors.New("backup envelope has an unsupported magic or version")
	}
	ciphertextLength := binary.BigEndian.Uint64(header[fixedHeaderSize+saltSize:])
	if ciphertextLength < gcmOverhead || ciphertextLength > uint64(MaxArchiveSize-envelopeHeadSize) {
		return nil, errors.New("backup envelope declares an invalid ciphertext size")
	}
	if ciphertextLength != uint64(len(envelope)-envelopeHeadSize) {
		return nil, errors.New("backup envelope is truncated or contains trailing data")
	}

	aead, derivedKey, err := archiveAEAD(rootKey, header[fixedHeaderSize:fixedHeaderSize+saltSize])
	if err != nil {
		return nil, err
	}
	defer clear(derivedKey)
	plaintext, err := aead.Open(nil, nil, envelope[envelopeHeadSize:], header)
	if err != nil {
		return nil, ErrAuthentication
	}
	return plaintext, nil
}

func archiveAEAD(rootKey, salt []byte) (cipher.AEAD, []byte, error) {
	derivedKey, err := hkdf.Key(sha256.New, rootKey, salt, backupKDFInfo, RootKeySize)
	if err != nil {
		return nil, nil, fmt.Errorf("derive backup encryption key: %w", err)
	}
	block, err := aes.NewCipher(derivedKey)
	if err != nil {
		clear(derivedKey)
		return nil, nil, fmt.Errorf("initialize backup encryption: %w", err)
	}
	aead, err := cipher.NewGCMWithRandomNonce(block)
	if err != nil {
		clear(derivedKey)
		return nil, nil, fmt.Errorf("initialize backup authentication: %w", err)
	}
	return aead, derivedKey, nil
}

func validateRootKey(rootKey []byte) error {
	if len(rootKey) != RootKeySize {
		return errors.New("root backup key must be exactly 32 bytes")
	}
	return nil
}

func validateSource(source Source) error {
	if len(source.StateJSON) < 1 || len(source.StateJSON) > MaxControlStateSize {
		return errors.New("control state has an invalid size")
	}
	if len(source.IdentityStateJSON) < 1 || len(source.IdentityStateJSON) > MaxIdentityStateSize {
		return errors.New("identity state has an invalid size")
	}
	if len(source.MasterKey) != RootKeySize {
		return errors.New("master key must be exactly 32 bytes")
	}
	if err := validateAdminToken(source.AdminToken); err != nil {
		return err
	}
	if source.ControlVersion == 0 {
		return errors.New("control version must be positive")
	}
	if !validSchemaName(source.IdentitySchema) {
		return errors.New("identity schema is invalid")
	}
	return nil
}

func validateAdminToken(token []byte) error {
	if len(token) < 32 || len(token) > 4096 {
		return errors.New("admin token must contain 32-4096 printable ASCII characters")
	}
	for _, character := range token {
		if character < 0x21 || character > 0x7e {
			return errors.New("admin token must contain 32-4096 printable ASCII characters")
		}
	}
	return nil
}

func encodePlaintext(manifestJSON []byte, source Source) ([]byte, error) {
	if len(manifestJSON) == 0 || len(manifestJSON) > maxManifestSize {
		return nil, errors.New("backup manifest exceeds its size limit")
	}
	master := make([]byte, base64.RawURLEncoding.EncodedLen(len(source.MasterKey))+1)
	base64.RawURLEncoding.Encode(master[:len(master)-1], source.MasterKey)
	master[len(master)-1] = '\n'
	admin := make([]byte, len(source.AdminToken)+1)
	copy(admin, source.AdminToken)
	admin[len(admin)-1] = '\n'
	defer clear(master)
	defer clear(admin)

	total := manifestSizeSize + len(manifestJSON) + len(source.StateJSON) + len(source.IdentityStateJSON) + len(master) + len(admin)
	if total+gcmOverhead+envelopeHeadSize > MaxArchiveSize {
		return nil, errors.New("backup archive exceeds its size limit")
	}
	plaintext := make([]byte, total)
	binary.BigEndian.PutUint32(plaintext[:manifestSizeSize], uint32(len(manifestJSON)))
	offset := manifestSizeSize
	offset += copy(plaintext[offset:], manifestJSON)
	offset += copy(plaintext[offset:], source.StateJSON)
	offset += copy(plaintext[offset:], source.IdentityStateJSON)
	offset += copy(plaintext[offset:], master)
	copy(plaintext[offset:], admin)
	return plaintext, nil
}
